// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWhBaGXpQjiFzkQ9XRuvGwEgKJrPWypNY',
    appId: '1:763751005076:android:d668a114c8753c2e56ed81',
    messagingSenderId: '763751005076',
    projectId: 'bioway-mexico',
    storageBucket: 'bioway-mexico.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeXT8JdQt-s5Ibi4cGto1OU1ZmZxvJsWw',
    appId: '1:763751005076:ios:c5fa7215e6ea4c4856ed81',
    messagingSenderId: '763751005076',
    projectId: 'bioway-mexico',
    storageBucket: 'bioway-mexico.firebasestorage.app',
    iosBundleId: 'com.biowaymexico.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGjPuE5BqzQx-FldRHr3kVeG0s361qSpo',
    appId: '1:763751005076:web:a0f4a39e1e9bf05b56ed81',
    messagingSenderId: '763751005076',
    projectId: 'bioway-mexico',
    authDomain: 'bioway-mexico.firebaseapp.com',
    storageBucket: 'bioway-mexico.firebasestorage.app',
  );

}